apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: my-python-app
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres:5432/mydatabase"