apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:13
        command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
        - name: python-app
          image: my-python-app
          ports:
            - containerPort: 50051
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: DATABASE_URL
              value: "postgresql://user:$(POSTGRES_PASSWORD)@postgres:5432/mydatabase"