apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # The password will be read from a local file by Tilt
  # and will not be checked into version control.
  password: ""